config/routes.rb
Rails.application.routes.draw do
  resources :clients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'clients#index'

  resource :clients
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
    has_many :enfants, dependent: :destroy
    accepts_nested_attributes_for :enfants, allow_destroy: true
end

app/models/enfant.rb
class Enfant < ApplicationRecord
  belongs_to :client
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
    @client.enfants.build
  end

  # GET /clients/1/edit
  def edit
      @client.enfants.build
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:Prenom, :Nom, :DateNaissance, :NAS, :NombreEnfants, :CompteTaxesProprietaire)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_enfant.html.erb
<div class="field">
  <%= form.label :Prenom %>
  <%= form.number_field :Prenom, id: :enfant_Prenom %>
</div>

<div class="field">
  <%= form.label :Nom %>
  <%= form.number_field :Nom, id: :enfant_Nom %>
</div>

<div class="field">
  <%= form.label :DateNaissance %>
  <%= form.datetime_select :DateNaissance, id: :enfant_DateNaissance %>
</div>

app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Prenom %>
    <%= form.text_field :Prenom, id: :client_Prenom %>
  </div>

  <div class="field">
    <%= form.label :Nom %>
    <%= form.text_field :Nom, id: :client_Nom %>
  </div>

  <div class="field">
    <%= form.label :DateNaissance %>
    <%= form.datetime_select :DateNaissance, id: :client_DateNaissance %>
  </div>

  <div class="field">
    <%= form.label :NAS %>
    <%= form.text_field :NAS, id: :client_NAS %>
  </div>

  <div class="field">
    <%= form.label :NombreEnfants %>
    <%= form.number_field :NombreEnfants, id: :client_NombreEnfants %>
  </div>

  <div class="field">
    <%= form.label :CompteTaxesProprietaire %>
    <%= form.number_field :CompteTaxesProprietaire, id: :client_CompteTaxesProprietaire %>
  </div>

  <div class="field">
      <%= form.fields_for :enfants do |builder| %>
          <% render 'enfant', form: builder %>
      <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clients</h1>

<table>
  <thead>
    <tr>
      <th>Prenom</th>
      <th>Nom</th>
      <th>Datenaissance</th>
      <th>Nas</th>
      <th>Nombreenfants</th>
      <th>Comptetaxesproprietaire</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.Prenom %></td>
        <td><%= client.Nom %></td>
        <td><%= client.DateNaissance %></td>
        <td><%= client.NAS %></td>
        <td><%= client.NombreEnfants %></td>
        <td><%= client.CompteTaxesProprietaire %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Prenom:</strong>
  <%= @client.Prenom %>
</p>

<p>
  <strong>Nom:</strong>
  <%= @client.Nom %>
</p>

<p>
  <strong>Datenaissance:</strong>
  <%= @client.DateNaissance %>
</p>

<p>
  <strong>Nas:</strong>
  <%= @client.NAS %>
</p>

<p>
  <strong>Nombreenfants:</strong>
  <%= @client.NombreEnfants %>
</p>

<p>
  <strong>Comptetaxesproprietaire:</strong>
  <%= @client.CompteTaxesProprietaire %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>INF27507Tp01</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>